<a href="https://colab.research.google.com/github/mgraudina/WoTech-2024-PHYTON/blob/main/07_06_Pandas_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**L13: Exploratory data analysis with Pandas library |**

1. Pandas Series vs Pandas DataFrames
2. Creating Pandas Series and DataFrames from lists, dictionaries and string objects
3. DataFrame exploration with built in methods
4. Indexing, slicing and selection

+ Repeating and using topics from previous lecture:

1. Reading CSV file as DataFrame
2. Performing simple operations on DataFrames
3. Writing DataFrame to a CSV file

**Data & Analytics Notebooks**

https://colab.google/notebooks/

Exploratory Data Analysis with Phyton

https://colab.research.google.com/github/Tanu-N-Prabhu/Python/blob/master/Exploratory_data_Analysis.ipynb

In [ ]:
# Structure of Pandas
# There are two types of Objects: DATAFRAMES AND SERIES (in Pandas)
# Difference btw list and dictionary --> List: indexing; Dictionary: key-value pairs

# DataFrame has two coordinates: x and y
# DataFrame --> collection of series, has several columns
# Series --> has always only one column! Used when huge set of data needs to be stored in one column

In [ ]:
import pandas as pd

In [ ]:
data_list = [1,2,3,4,5] # list
print(data_list)

[1, 2, 3, 4, 5]

### Pandas SERIES

In [ ]:
series_from_list = pd.Series(data_list) # create series
print(series_from_list)

# first column = index; second = values of column

0    1
1    2
2    3
3    4
4    5
dtype: int64

### Pandas DATAFRAME

In [ ]:
dataframe_from_list = pd.DataFrame(data_list) # create dataframe
print(dataframe_from_list)

# first column = index; second = values; 0 on top of second = index of column

   0
0  1
1  2
2  3
3  4
4  5

### Pandas SERIES FROM DICTIONARY

In [ ]:
data_dict = {'A': 10, 'B': 20, 'C': 30, 'D': 40, 'E': 50} # dictionary object key-value pairs

series_from_dict = pd.Series(data_dict)
print(series_from_dict)

# dtype: int64 --> integer values
# keys are indexes, otherwise it would be default: 0,1...

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [ ]:
csv_data = "1,2,3,4,5" # string
csv_data.split(",") # split it to list, it is not string any more

['1', '2', '3', '4', '5']

In [ ]:
series_from_list_split = pd.Series(csv_data.split(","))
print(series_from_list_split)

0    1
1    2
2    3
3    4
4    5
dtype: object

### DATAFRAMES

In [ ]:
data_list = [
    ['John', 30, 68.5, True, 95.5],
    ['Alice', 25, 63.2, False, 88.0],
    ['Bob', 35, 71.0, True, 76.5],
    ['Eve', 28, 65.8, False, 92.0],
    ['Charlie', 40, 72.3, False, 87.5]
]

# nested list (list of lists, embedded)

column_names = ["Name", "Age", "Weight", "Is Student", "Score"] # column names defined by us
pd.DataFrame(data_list, columns=column_names)

      Name  Age  Weight  Is Student  Score
0     John   30    68.5        True   95.5
1    Alice   25    63.2       False   88.0
2      Bob   35    71.0        True   76.5
3      Eve   28    65.8       False   92.0
4  Charlie   40    72.3       False   87.5

### Working with a CSV file

In [ ]:
df = pd.read_csv("/content/transaction_dataset.csv") # we have read in the file

In [ ]:
df.head() # first 5 rows of dataframe (default, if not marked n=10)

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
1,26381,Michelle,Phelps,NaN,24/10/1985,2552.72,17/07/2023,"Peck, Spence and Young",Travel
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics

In [ ]:
df.tail() # last 5 rows of dataframe

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
49995,891845,Christine,Leach,F,21/10/1997,108.74,30/08/2023,Alexander Ltd,Market
49996,800560,Anna,Allen,F,21/10/1999,133.66,03/05/2023,Knapp-Calhoun,Cosmetic
49997,133285,Nicole,Franklin,M,26/10/1979,464.29,12/02/2023,"Cantrell, Haynes and Ballard",Market
49998,616122,Maria,Keller,M,25/10/1981,472.57,25/03/2023,"Wilson, Jackson and Beard",Market
49999,832184,Billy,Walker,F,31/10/1958,270.67,20/05/2023,Combs LLC,Market

In [ ]:
df.shape # number of rows and columns # gives tuple

(50000, 9)

In [ ]:
df.sample(5) # random 5 samples of dataframe

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
31343,491732,Tammy,Bryant,F,01/11/1952,180.32,29/09/2023,Johnson-Nixon,Cosmetic
44197,555786,Hannah,Hart,M,26/10/1978,2836.67,23/05/2023,Gonzales-Mahoney,Travel
43176,965941,Elizabeth,Davidson,M,31/10/1959,180.98,02/09/2023,"Hall, Bass and Perez",Clothing
22436,811448,Kim,Armstrong,M,24/10/1986,176.11,22/08/2023,Powers-Banks,Clothing
20840,952592,Amy,White,F,26/10/1979,418.97,19/01/2023,Townsend Inc,Electronics

In [ ]:
df.info() # column names, data types (Dtype), how many values NaN (Non-Null)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer ID         50000 non-null  int64
 1   Name                50000 non-null  object
 2   Surname             50000 non-null  object
 3   Gender              44953 non-null  object
 4   Birthdate           50000 non-null  object
 5   Transaction Amount  50000 non-null  float64
 6   Date                50000 non-null  object
 7   Merchant Name       50000 non-null  object
 8   Category            50000 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 3.4+ MB

In [ ]:
df.describe() # summary of statistics of integers/floats

        Customer ID  Transaction Amount
count   50000.00000        50000.000000
mean   500136.79696          442.119239
std    288232.43164          631.669724
min        29.00000            5.010000
25%    251191.50000           79.007500
50%    499520.50000          182.195000
75%    749854.25000          470.515000
max    999997.00000         2999.880000

In [ ]:
df.describe(include="object") # summary statistics of strings

,Name,Surname,Gender,Birthdate,Date,Merchant Name,Category
count,50000,50000,44953,50000,50000,50000,50000
unique,690,1000,2,58,287,36939,6
top,Michael,Smith,F,01/11/1954,30/06/2023,Smith Ltd,Restaurant
freq,1167,1095,22713,914,200,69,8413

In [ ]:
df.head()

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
1,26381,Michelle,Phelps,NaN,24/10/1985,2552.72,17/07/2023,"Peck, Spence and Young",Travel
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics

In [ ]:
# How to select 1x COLUMN in a DataFrame?

df["Gender"]

0          F
1        NaN
2          M
3          M
4          F
        ...
49995      F
49996      F
49997      M
49998      M
49999      F
Name: Gender, Length: 50000, dtype: object

In [ ]:
# How many UNIQUE values?

df["Gender"].unique()

array(['F', nan, 'M'], dtype=object)

In [ ]:
# WAYS TO ACCESS THE SAME COLUMN

df["Gender"]
# we access column by name, we can access several columns
# you can use column name with space, with dot (.) approach it is not possible

df.Gender
# we access the same column
# accessing column with attribute

df.iloc[:, 3]
# index location, row and column
# accessing column with index

0          F
1        NaN
2          M
3          M
4          F
        ...
49995      F
49996      F
49997      M
49998      M
49999      F
Name: Gender, Length: 50000, dtype: object

In [ ]:
# VALUE COUNTS

df["Gender"].value_counts(dropna=False)
# call method
# will show empty NaN values
# dropna = we define we do not want to drop NaN values

Gender
F      22713
M      22240
NaN     5047
Name: count, dtype: int64

In [ ]:
# EMPTY VALUES

df.isna() # is na = wether value is empty. binary. False = 0; True = 1 (empty)

df.isna().sum() #sums empty values

df.notna().sum() # sums non empty values

df.notna().all() # checks if all values are filled in

Customer ID            True
Name                   True
Surname                True
Gender                False
Birthdate              True
Transaction Amount     True
Date                   True
Merchant Name          True
Category               True
dtype: bool

In [ ]:
# DROP empty values

df.dropna() # does not override

df.dropna(inplace=True) # will override

In [ ]:
# SAVE the cleaned file

df.to_csv("cleaned_data.csv")

In [ ]:
df

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
1,26381,Michelle,Phelps,NaN,24/10/1985,2552.72,17/07/2023,"Peck, Spence and Young",Travel
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics
...,...,...,...,...,...,...,...,...,...
49995,891845,Christine,Leach,F,21/10/1997,108.74,30/08/2023,Alexander Ltd,Market
49996,800560,Anna,Allen,F,21/10/1999,133.66,03/05/2023,Knapp-Calhoun,Cosmetic
49997,133285,Nicole,Franklin,M,26/10/1979,464.29,12/02/2023,"Cantrell, Haynes and Ballard",Market
49998,616122,Maria,Keller,M,25/10/1981,472.57,25/03/2023,"Wilson, Jackson and Beard",Market
49999,832184,Billy,Walker,F,31/10/1958,270.67,20/05/2023,Combs LLC,Market